# SPDX-FileCopyrightText: 2026 Govind Singh
# SPDX-License-Identifier: GPL-2.0-only

version = 1
SPDX-PackageName = "edge-computing-nixos"
SPDX-PackageSupplier = "Govind Singh"
SPDX-PackageDownloadLocation = "https://github.com/YOUR_ORG/edge-computing-nixos"

[[annotations]]
path = [
  ".gitignore",
  "flake.lock",
  "LICENSES/**",
  "patch/**",
]
precedence = "aggregate"
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileCopyrightText = "2026 Govind Singh"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-License-Identifier = "GPL-2.0-only"
SPDX-FileCopyrightText = "2026 Govind Singh"
